### ISSUE TITLE
Version Bump [JOSS]

### ISSUE THREAD

**Issue by HaoZeke** [matbesancon/BilevelOptimization.jl#7]
Part of the ongoing JOSS review, https://github.com/openjournals/joss-reviews/issues/1278.
Could you please update the version submitted? [0.1.0 -> 0.1.1 or greater]

**Comment by matbesancon** [comment]
@HaoZeke I just bumped the package to 0.2.0, you mean bumping on https://github.com/openjournals/joss-reviews/issues/1278? I didn't find how to do that

**Comment by HaoZeke** [comment]
I've bumped the version being reviewed and can close this if you confirm that the `paper.md` reflects the changes and features included upto v0.2.0

**Comment by matbesancon** [comment]
yes that's the case

**Comment by HaoZeke** [comment]
Thanks for the clarification.
